# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rescat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rescat
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Kingfisher'
    pod 'SnapKit'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'AACarousel'
    pod 'MXSegmentedPager'
    pod 'ImageSlideshow', '~> 1.6'
    pod 'ImageSlideshow/Kingfisher'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'UITextView+Placeholder'
    pod 'SwiftGifOrigin', '~> 1.6.1'

end
